name: Python API CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r api/requirements_dev.txt
    - name: Static Analysis via mypy
      working-directory: ./api
      run: mypy --strict waitlist *.py
    - name: Code Style checks via black
      working-directory: ./api
      run: black --check waitlist *.py
    - name: Code Style checks via pylint
      working-directory: ./api
      run: pylint waitlist *.py
